spring.data.mongodb.host: localhost
spring.data.mongodb.database: test
spring.data.mongodb.port: 27017

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: rabbit_user
        password: rabbit_pass

rabbitmq:
    queue-name: iot_queue